# This is the manifest file for building CrysFML 
# It is better to comment the part corresponding to executables in order to construct
# the library totally independent of the programs using it. An error occurs if one uses
#  
#
#
name = "CrysFML"
version = "0.1.0"
license = "LGPL"
author = "Juan Rodriguez-Carvajal, Javier Gonzalez-Platas, Nebil A. Katcho"
maintainer = "jrc@ill.eu"
copyright = "Copyright 2022, Juan Rodriguez-Carvajal, Javier Gonzalez-Platas, Nebil A. Katcho"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[install]
library = true

[library]
source-dir = "Src"
include-dir = "Src"
#
# The lines above are enough for building the library using the scripts make_CrysFML_fpm.bat/make_CrysFML_fpm.sh
#
#==============================================================================================
# WARNING! For building the executables uncomment the lines below once the library is installed
#==============================================================================================
#
# Some executables from Program_Examples
#

[[executable]]
name="cryscalcon"
source-dir="Program_Examples/Cryst_calculator_console"
main="cryscalc_con.f90"

[[executable]]
name="hkl_gen"
source-dir="Program_Examples/hkl_gen"
main="hkl_gen.f90"

[[executable]]
name="Formal_Charges"
source-dir="Program_Examples/BondStr/FormalCharges"
main="Formal_Charges.f90"

[[executable]]
name="Bond_Str"
source-dir="Program_Examples/BondStr/Src"
main="Bond_Str.f90"

[[executable]]
name="Similar"
source-dir="Program_Examples/SimilarityTransformations"
main="Similar.f90"

[[executable]]
name="space_group_info"
source-dir="Program_Examples/SpaceGroups"
main="space_group_info.f90"

[[executable]]
name="subgroups"
source-dir="Program_Examples/SpaceGroups"
main="subgroups.f90"

#
# Structure factors
#

[[executable]]
name="Calc_mSfac"
source-dir="Program_Examples/StructureFactors"
main="Calc_mSfac.f90"

[[executable]]
name="Calc_Sfac"
source-dir="Program_Examples/StructureFactors"
main="Calc_Sfac.f90"

#
# Structures_GlobalOptimization
#
[[executable]]
name="GLOpSAnn"
source-dir="Program_Examples/Structures_GlobalOptimization/Src"
main="GLOpSAnn.f90"

#
# Metric
#
#[[executable]]
#name="Get_Conv_Cell"
#source-dir="Program_Examples/Metrics"
#main="Get_Conv_Cell.f90"

[[executable]]
name="search_cellrelations"
source-dir="Program_Examples/Metrics"
main="search_cellrelations.f90"

#
# Magnetic examples, polarimetry
#
[[executable]]
name="MagPolar3D"
source-dir="Program_Examples/Magnetism"
main="MagPolar3D.f90"

#[[executable]]
#name="magref"
#source-dir="Program_Examples/Magnetism"
#main="magref.f90"

#[[executable]]
#name="Schwinger"
#source-dir="Program_Examples/Magnetism"
#main="Schwinger.f90"

[[executable]]
name="Moment"
source-dir="Program_Examples/Magnetism/Moment"
main="moment.f90"

#[[executable]]
#name="MagOptim"
#source-dir="Program_Examples/Magnetism/MagOptim_v4"
#main="MagOptim.f90"

#
# Magnetic package Simbo, EnerMag, Phase_Diagram and MC_Mag
#
[[executable]]
name="Simbo"
source-dir="Program_Examples/Simbo-Enermag"
main="Simbo.f90"

[[executable]]
name="EnerMag"
source-dir="Program_Examples/Simbo-Enermag"
main="EnerMag.f90"

[[executable]]
name="Phase_Diagram"
source-dir="Program_Examples/Simbo-Enermag"
main="Phase_Diagram.f90"

[[executable]]
name="MC_Mag"
source-dir="Program_Examples/Simbo-Enermag/MC_Mag"
main="mc_mag.f90"

#
# Faults Program
#
[[executable]]
name="DIFFaX2FAULTS"
source-dir="Program_Examples/Faults/DIFFaX2FAULTS"
main="DIFFaX2FAULTS.f90"

[[executable]]
name="Faults"
source-dir="Program_Examples/Faults/Src"
main="Faults.f90"

#
# Powder Patterns
#
[[executable]]
name="Simple_Calc_Mag_Powder"
source-dir="Program_Examples/PowderPattern"
main="Simple_Calc_Mag_Powder.f90"

[[executable]]
name="Calc_Powder"
source-dir="Program_Examples/PowderPattern"
main="calc_powder.f90"

[[executable]]
name="Simple_Calc_Powder"
source-dir="Program_Examples/PowderPattern"
main="Simple_calc_powder.f90"

[[executable]]
name="Correct_Cells"
source-dir="Program_Examples/PowderPattern"
main="corr_cells.f90"

[[executable]]
name="Laue_Powder"
source-dir="Program_Examples/PowderPattern"
main="Laue_powder.f90"


